language: node_js
node_js:
    - "8"
    - "10"
env:
    - REACT=16.x
script:
    - npm test
    - npm run coverage
before_install:
    - npm install
    - npm install react react-dom
after_script:
    npm install coveralls && nyc report --reporter=text-lcov | coveralls
